Update Bonsai size and behavior
hyperledger/besu-docs pull request #1005
Opened 2022-03-29 17:49 UTC by rolandtyler

Signed-off-by: Roland Tyler <roland.tyler@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [x] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [x] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [x] you fixed all the issues raised by the tests, if any.
- [x] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change
Update Bonsai storage size.
Added note about `--bonsai-maximum-back-layers-to-load`

## Issue fixed
Fixes #996 

## Impacted parts 

### For content changes

- [x] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

2022-03-29 19:14 UTC, matkt requested changes

2022-03-29 19:14 UTC, matkt commented on docs/Concepts/Data-Storage-Formats.md
> +    Using `--bonsai-maximum-back-layers-to-load` does not affect the size of the date being stored, only how far back to load.
I think you want to Say database ?

2022-03-29 19:16 UTC, rolandtyler commented on docs/Concepts/Data-Storage-Formats.md
> +    Using `--bonsai-maximum-back-layers-to-load` does not affect the size of the date being stored, only how far back to load.
Fixed

2022-03-29 20:22 UTC, matkt approved these changes

2022-03-30 16:59 UTC, alexandratran approved these changes

2022-03-30 16:59 UTC, alexandratran commented on docs/Concepts/Data-Storage-Formats.md
> +    This means there is no "safe minimum" value to use with this option.
```suggestion
    Using `--bonsai-maximum-back-layers-to-load` doesn't affect the size of the database being stored, only how far back to load.
    This means there's no "safe minimum" value to use with this option.
```

2022-03-30 17:15 UTC, rolandtyler commented on docs/Concepts/Data-Storage-Formats.md
> +    This means there is no "safe minimum" value to use with this option.
Fixed

2022-03-30 17:17 UTC, merged