Remove Clique
hyperledger/besu-docs pull request #1037
Opened 2022-05-16 20:00 UTC by rolandtyler

Signed-off-by: Roland Tyler <roland.tyler@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu documentation quality standard.

### Before creating the pull request

Make sure that:

- [x] [All commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] You've read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] You've [previewed your changes locally](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation).

## Describe the change
Remove Clique tutorials and references

## Issue fixed
Fixes #1034

## Impacted parts

For content changes:

- [x] Documentation content
- [x] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example, lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [x] You've fixed any issues raised by the tests.
- [x] You've [previewed your changes on Read the Docs](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation)
  and added a [preview link](#preview).

## Preview

2022-05-20 00:34 UTC, macfarla reviewed
Can you make a separate PR for changing the tutorials over to IBFT2? Still not sure if we can totally remove clique but we can remove it from tutorials.

2022-05-20 00:34 UTC, macfarla commented on docs/Tutorials/Permissioning/Getting-Started-Onchain-Permissioning.md
> +This tutorial configures permissioning on a [IBFT 2.0 proof of authority (PoA)] network.
The changes to this tutorial to change from Clique to IBFT2 - could you make that a separate PR?

2022-05-20 00:34 UTC, macfarla commented on docs/Tutorials/Permissioning/Upgrade-Permissioning-Contract.md
> -        besu --data-path=data --genesis-file=../cliqueGenesis.json --permissions-accounts-contract-enabled --permissions-accounts-contract-address "0x0000000000000000000000000000000000008888" --permi
ditto - include this in the permissioning tutorial change PR

2022-05-20 00:34 UTC, macfarla commented on docs/Tutorials/Permissioning/Create-Permissioned-Network.md
> +uses the [IBFT 2.0 proof of authority consensus protocol].
ditto here

2022-06-28 14:46 UTC, shemnon requested changes
Changing tutorials over to QBFT or IBFT2 is fine.

However Clique is still a mandated protocol in the current as well as the pending draft of the EEA Client Sepcification (https://entethalliance.github.io/client-spec/spec.html#sec-consensus-sublayer).  Since Besu was founded on EEA compatibility we have a requirement that clique must be implemented.  Scrubbing documentation runs counter to that obligation.

When The EEA spec removes clique as a MUST then we can change code and scrub documentation, until then we should continue to document it.

2022-06-28 17:11 UTC, rolandtyler commented
Closing per comment on EEA requirement

2022-06-28 17:11 UTC, closed without merging