Snap sync initial documentation
hyperledger/besu-docs pull request #1038
Opened 2022-05-17 01:17 UTC by alexandratran

Signed-off-by: Alexandra Tran <alexandra.tran@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu documentation quality standard.

### Before creating the pull request

Make sure that:

- [x] [All commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] You've read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] You've [previewed your changes locally](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation).

## Describe the change

Document snap sync - what is is, how to use it. Will expand on conceptual content in a future PR (added issue here: #1052).

## Issue fixed

fixes #1033

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example, lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [x] You've fixed any issues raised by the tests.
- [x] You've [previewed your changes on Read the Docs](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation)
  and added a [preview link](#preview).

## Preview

https://hyperledger-besu--1038.org.readthedocs.build/en/1038/Concepts/Node-Types/#run-a-full-node
https://hyperledger-besu--1038.org.readthedocs.build/en/1038/Reference/CLI/CLI-Syntax/#sync-mode
https://hyperledger-besu--1038.org.readthedocs.build/en/1038/Concepts/Data-Storage-Formats/#syncing-nodes

2022-05-17 11:24 UTC, NicolasMassart reviewed
I added some initial comments

2022-05-17 16:40 UTC, alexandratran commented on docs/Reference/CLI/CLI-Syntax.md
> +[snap synchronization](../../Concepts/Node-Types.md#snap-synchronization).
Noted. However, it seems (from Discord conversations) that snap sync is the recommended option, even in some production environments, which is unusual for an experimental feature. A warning about a feature being experimental usually comes with a recommendation to only use it for development/testing.

2022-05-17 17:21 UTC, alexandratran commented on docs/Concepts/Node-Types.md
> +Full sync starts from the genesis block and reprocesses all transactions.
This is noted at the top of this page (lines 18-19).

2022-05-23 23:11 UTC, macfarla commented on docs/Concepts/Node-Types.md
> +Instead of downloading the [state trie](Data-Storage-Formats.md) node by node, snap sync downloads the contiguous chunks
s/the contiguous/contiguous

2022-05-23 23:11 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
>    `FAST` is also the default if connecting to Ethereum Mainnet by not specifying the [`--network`](#network) and
would this be clearer -
  `FAST` is also the default if running besu on the default network (Ethereum Mainnet) by specifying neither network or genesis file

2022-05-23 23:11 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
> +    If your snap sync completes successfully, you should have the correct world state.
"should" here makes it sound doubtful

2022-05-31 07:26 UTC, matkt requested changes

2022-05-31 07:26 UTC, matkt commented on docs/Concepts/Data-Storage-Formats.md
> +With forest mode, your node can fast or snap sync to other nodes and other nodes can fast or snap sync to your node.
Besu cannot be snapsync as a server in bonsai or forest
Besu can be fastsync as a server as long as we sync our node with fastsync or snapsync but only with forest

next step will be to implement snapsync as a server

2022-06-01 07:00 UTC, matkt requested changes

2022-06-01 19:01 UTC, alexandratran commented on docs/Concepts/Data-Storage-Formats.md
> +After Bonsai as a snap sync server is implemented, other nodes will be able to fast or snap sync to a snap synced forest
Good call, changed to a table

2022-06-02 23:18 UTC, bgravenorst reviewed
General comment, should we add a section in [starting a node](https://besu.hyperledger.org/en/latest/HowTo/Get-Started/Starting-node/) discussing the syncing options?

Otherwise looks good, with a few minor comments.

2022-06-02 23:18 UTC, bgravenorst commented on docs/Concepts/Data-Storage-Formats.md
> +| Data storage format | Sync mode | Can other nodes sync to your node? |
Would adding the DB size to the table add value?

2022-06-03 00:52 UTC, macfarla approved these changes
couple of comments, LGTM overall

2022-06-03 00:52 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
>      ```
since we're recommending X_SNAP but the default is FAST, should the examples ^ be changed to use X_SNAP?

2022-06-03 00:52 UTC, macfarla commented on docs/Concepts/Node-Types.md
> +[`--network`](../Reference/CLI/CLI-Syntax.md#network) and [`--genesis-file`](../Reference/CLI/CLI-Syntax.md#genesis-file)
s/and/or

2022-06-03 00:52 UTC, macfarla commented on docs/Concepts/Data-Storage-Formats.md
> +The following table shows the ways you can run a full node with the different data storage formats using
why do we have "run a full node" here - what does "full" mean?

2022-06-03 08:12 UTC, matkt commented on docs/Concepts/Node-Types.md
> +trie as possible, and reconstructs the trie locally.
Matt nelson is preparing a blog about the new ways of sync. maybe you can see with him if there are already things of this kind

2022-06-03 20:06 UTC, alexandratran commented on docs/Concepts/Node-Types.md
> +trie as possible, and reconstructs the trie locally.
Added a new issue here #1052. I'm in touch with Matt about his blog post 👍

2022-06-03 20:29 UTC, merged