Doc updated engine options and edit CLI page
hyperledger/besu-docs pull request #1041
Opened 2022-05-21 08:01 UTC by alexandratran

## Pull request checklist

Use the following list to make sure your PR fits the Besu documentation quality standard.

### Before creating the pull request

Make sure that:

- [x] [All commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [x] You've read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] You've [previewed your changes locally](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation).

## Describe the change

Document updated engine options and make edits throughout CLI page for style consistency across boolean and host/port options.

## Issue fixed

fixes #1039 

## Impacted parts

For content changes:

- [x] Documentation content
- [ ] Documentation page organization

For tool changes:

- [ ] CircleCI workflow
- [ ] Build and QA tools (for example, lint or vale)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] Read the Docs configuration
- [ ] GitHub integration

## After creating your PR and tests have finished

Make sure that:

- [ ] You've fixed any issues raised by the tests.
- [ ] You've [previewed your changes on Read the Docs](https://wiki.hyperledger.org/display/BESU/Preview+the+documentation)
  and added a [preview link](#preview).

## Preview

2022-05-23 11:49 UTC, NicolasMassart approved these changes
Looks good to me.

2022-05-24 13:06 UTC, jflo commented on docs/Reference/CLI/CLI-Syntax.md
> +    engine-rpc-port=true
should read engine-rpc-enabled

2022-05-24 14:43 UTC, rolandtyler reviewed
We should also update this page https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Engine-API/

2022-05-24 18:49 UTC, rolandtyler approved these changes
lgtm

2022-05-26 19:54 UTC, garyschulte requested changes
recent changes invalidate some of these changes

2022-05-26 19:54 UTC, garyschulte commented on docs/HowTo/Interact/APIs/Engine-API.md
> +- Enable the Engine API using the [`--engine-rpc-enabled`](../../../Reference/CLI/CLI-Syntax.md#engine-rpc-enabled) option.
This is actually deprecated in the latest besu releases, and we instead defer to the presence or absence of `terminalTotalDifficulty` in the genesis config.  Relevant changes:

[engine-rpc-enabled parameter deprecated](https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java#L569-L574)

[log warning if engine-rpc-enabled used](https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java#L2115-L2119)

[merge config and therefore engine api deferring to genesis](https://github.com/hyperledger/besu/blob/main/besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java#L3192-L3201)

2022-05-26 19:54 UTC, garyschulte commented on docs/Reference/CLI/CLI-Syntax.md
> +
we should remove/rewrite this to indicate we are deferring to TTD for enabling engine-rpc-api

2022-05-26 20:23 UTC, garyschulte reviewed
LGTM, just a nitpick and a question

2022-05-26 20:23 UTC, garyschulte commented on docs/HowTo/Interact/APIs/Engine-API.md
> +To specify the port the Engine API service listens on over HTTP and WebSocket, use the
suggest `...service listens on for HTTP and WebSockets ...`.  Nitpicky though

2022-05-26 20:23 UTC, garyschulte commented on docs/HowTo/Interact/APIs/Engine-API.md
> +- [Enable the JSON-RPC API](API.md#enable-api-access).
it is possible I am just missing it, but where is this anchor?

2022-05-26 20:29 UTC, garyschulte commented on docs/HowTo/Interact/APIs/Engine-API.md
> +- [Enable the JSON-RPC API](API.md#enable-api-access).
NVM, found it :)

2022-05-26 20:30 UTC, garyschulte approved these changes
🚢

2022-05-26 20:34 UTC, jflo approved these changes

2022-05-26 20:34 UTC, merged