Update config for tx-pool-limit-by-account-percentage on pub nets, consider moving to both sides
hyperledger/besu-docs pull request #1256
Opened 2023-01-31 22:50 UTC by non-fungible-nelson

This updates the tx-pool-limit to the correct name for the parameter and provides a word of caution. Suggest that we copy this over to the private network side and call it out as well until we have a better parameterization default. We may be changing this shortly on Mainnet. I will ask @fab-10 to tag the docs team when he finishes his new transaction pool work. 

Signed-off-by: Matt Nelson <85905982+non-fungible-nelson@users.noreply.github.com>

2023-02-01 03:17 UTC, alexandratran approved these changes
Minor edits and added a note on the private networks start node page. LGTM.

2023-02-06 09:04 UTC, macfarla approved these changes

2023-02-06 10:03 UTC, fab-10 requested changes
Made 2 corrections

2023-02-06 10:03 UTC, fab-10 commented on docs/public-networks/reference/cli/options.md
> +The default is .1 or 10% of transactions from a single account to be kept in the pool.
The current default is .001 or 0.1%, that for the default size means max 5 txs per sender

2023-02-06 10:04 UTC, fab-10 commented on docs/public-networks/reference/cli/options.md
> +    --tx-pool-limit-by-account-percentage=<LONG>
we can also says that accepted values are in the range (0-1]

2023-03-02 19:23 UTC, non-fungible-nelson commented
@alexandratran any status?

2023-03-02 20:35 UTC, alexandratran commented
@non-fungible-nelson Sorry for the delay. Can you make the changes that @fab-10 requested? Then he needs to re-review. Otherwise I can make the changes probably tomorrow.

2023-03-02 20:39 UTC, non-fungible-nelson commented
I thought i accepted his changes? @fab-10 can you re-review?

2023-03-02 20:44 UTC, non-fungible-nelson reviewed
accepting changes

2023-03-02 20:44 UTC, alexandratran commented
@non-fungible-nelson no, he commented his change suggestions but didn't implement them. It looks like you resolved his comment without implementing.

2023-03-03 09:49 UTC, fab-10 commented on docs/public-networks/reference/cli/options.md
> +    --tx-pool-limit-by-account-percentage=<LONG>
```suggestion
    --tx-pool-limit-by-account-percentage=<DOUBLE>
```

2023-03-03 09:50 UTC, fab-10 commented on docs/public-networks/reference/cli/options.md
> +The default is .1 or 10% of transactions from a single account to be kept in the pool.
```suggestion
The maximum percentage of future transactions kept in the transaction pool, per account.
Accepted values are in the range (0-1]. The default is .001 or 0.1% of transactions from a single account to be kept in the pool.
```

2023-03-03 09:51 UTC, fab-10 commented
@non-fungible-nelson please check my suggested change and incorporate them

2023-03-03 16:36 UTC, fab-10 approved these changes

2023-03-03 20:21 UTC, merged