Documented debug_traceCall
hyperledger/besu-docs pull request #1439
Opened 2023-11-13 10:22 UTC by ATREAY

## Description
This pull request includes information about the **debug_traceCall** method.

## Issue
fixes: #1417

2023-11-15 03:31 UTC, Gabriel-Trintinalia requested changes
Some wording changes:

2023-11-15 03:31 UTC, Gabriel-Trintinalia commented on docs/public-networks/reference/api/index.md
> +Returns a detailed trace of the executed opcodes for a specific transaction.
```suggestion
Performs an eth_call within the execution environment of a given block, using the final state of its parent block as the base, and provides a detailed trace of the executed opcodes.
```

2023-11-15 03:31 UTC, Gabriel-Trintinalia commented on docs/public-networks/reference/api/index.md
> +- `requestContext`: _object_ - JSON-RPC request context with essential fields like `from`, `to`, `gas`, `gasPrice`, `value`, `data`, `nonce`.
```suggestion
`call`: _object_ - [transaction call object](objects.md#transaction-call-object)

`blockNumber` or `blockHash`: _string_ - hexadecimal or decimal integer representing a block number, block hash, or one of the string tags `latest`, `earliest`, `pending`, `finalized`, or `safe`, as described in [block parameter](../../how-to/use-besu-api/json-rpc.md#block-parameter)
```

2023-11-15 22:57 UTC, Gabriel-Trintinalia reviewed
Hi @ATREAY, lgtm, Could you please add this method to the trace object description in objects.md

2023-11-16 03:43 UTC, ATREAY commented
Hi @Gabriel-Trintinalia, I added the debug_traceCall method to the objects.md file. Can you take a look when you have a moment?

2023-11-16 03:44 UTC, Gabriel-Trintinalia approved these changes
lgtm

2023-11-16 20:56 UTC, alexandratran approved these changes

2023-11-16 20:56 UTC, alexandratran commented on docs/public-networks/reference/api/index.md
> +Performs an eth_call within the execution environment of a given block, using the final state of its parent block as the base, and provides a detailed trace of the executed opcodes.
```suggestion
Performs an [`eth_call`](#eth_call) within the execution environment of a given block, using the final state of its parent block as the base, and provides a detailed trace of the executed opcodes.
```

2023-11-16 21:17 UTC, merged