doc new fields for eth_getTransaction series of RPCs
hyperledger/besu-docs pull request #637
Opened 2021-03-17 01:55 UTC by alexandratran

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Add new fields to the three eth_getTransaction JSON-RPC samples.

## Issue fixed

fixes #602 

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-03-17 05:51 UTC, bgravenorst requested changes
Looks like you may need to update the Transaction object table as well. See https://besu.hyperledger.org/en/latest/Reference/API-Objects/#transaction-object

2021-03-19 08:31 UTC, NicolasMassart reviewed
Does it have to be added also to graphql results?
By the way, graphql result for eth_getTransactionByBlockHashAndIndex seems strange as it has nothing to do with the RPC result and doesn't provide info about the TX. Mistake?

@hyperledger/besu-docs-maintainers ?

2021-04-05 23:37 UTC, macfarla approved these changes
There's a typo (that you didn't make!) that would be good to fix as part of this PR. Otherwise LGTM

2021-04-05 23:37 UTC, macfarla commented on docs/Reference/API-Objects.md
> +| **chainId**          | Quantity            | [Chain ID](../Concepts/NetworkID-And-ChainID.md).                                          |
I just spotted typo a few lines up `eth_getTransactionsByBlockNumberAndIndex`

should be `eth_getTransactionByBlockNumberAndIndex` - I think it's related enough to this change to fix in the same PR

2021-04-06 05:53 UTC, merged