doc --rpc-http-max-active-connections option
hyperledger/besu-docs pull request #638
Opened 2021-03-17 02:29 UTC by alexandratran

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Add documentation for the --rpc-http-max-active-connection option

## Issue fixed

fixes #630 

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-03-17 03:32 UTC, bgravenorst commented on docs/Reference/CLI/CLI-Syntax.md
> +The maximum number of HTTP connections allowed for JSON-RPC. Once this limit is reached, incoming connections will be rejected. The default is 80.
Minor comment: Try and rephrase without "will". It's one of the words on our do not use list :)

2021-03-17 03:37 UTC, bgravenorst requested changes
Minor suggestions. Also, similar to the other issue  I'm not sure quotes ("") are required around integers in the config file. But we seem pretty inconsistent in the docs.

2021-03-17 07:39 UTC, NicolasMassart commented on docs/Reference/CLI/CLI-Syntax.md
> +    rpc-http-max-active-connections="100"
the TOML syntax for integers is indeed without quotes, see https://toml.io/en/

2021-03-17 07:39 UTC, NicolasMassart commented on docs/Reference/CLI/CLI-Syntax.md
> +    ```bash
```suggestion
    ```toml
```

2021-03-18 07:45 UTC, NicolasMassart approved these changes

2021-03-18 07:58 UTC, bgravenorst approved these changes
Looks good to me.

2021-03-18 08:19 UTC, merged