doc --rpc-ws-max-active-connections option
hyperledger/besu-docs pull request #639
Opened 2021-03-17 02:40 UTC by alexandratran

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Add documentation for the --rpc-ws-max-active-connection option

## Issue fixed

fixes #631 

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-03-17 03:21 UTC, bgravenorst commented on docs/Reference/CLI/CLI-Syntax.md
> +The maximum number of WebSocket connections allowed for JSON-RPC. Once this limit is reached, incoming connections will be rejected. The default is 80.
Minor comment: Try and rephrase without "will".

2021-03-17 03:24 UTC, bgravenorst requested changes
Minor change required.

Also, I'm not sure quotes ("") are required around integers in the config file. But we seem pretty inconsistent in the docs.

2021-03-17 07:49 UTC, NicolasMassart commented
> Minor change required.
> 
> Also, I'm not sure quotes ("") are required around integers in the config file. But we seem pretty inconsistent in the docs.

No, quotes should not be used around numbers. see https://toml.io/en/

2021-03-17 08:01 UTC, NicolasMassart commented on docs/Reference/CLI/CLI-Syntax.md
> +    rpc-ws-max-active-connections="100"
numbers must not have quotes in TOML

2021-03-18 07:52 UTC, NicolasMassart approved these changes

2021-03-18 07:59 UTC, bgravenorst approved these changes
Looks good to me

2021-03-18 08:00 UTC, merged