doc transaction types and object fields for EIPs 2930 and 1559
hyperledger/besu-docs pull request #738
Opened 2021-06-15 19:39 UTC by alexandratran

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

Update API Objects to include new fields for typed transactions (EIPs 2718, 2930, and 1559).

Add Transaction Types concept page.

## Issue fixed

fixes #737 

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-06-16 22:45 UTC, garyschulte requested changes
Looks good, minor feedback about 'compatibility'

2021-06-16 22:45 UTC, garyschulte commented on docs/Concepts/Transactions/Transaction-Types.md
> +[EIP-1559 fee market changes](#eip1559-transactions).
perhaps better stated as 'Legacy transactions are not compatible with parameters introduced by access list transactions or 1559 fee market transactions.  

Legacy transactions will continue to work post-1559, so the usage of 'compatibility' might be confusing.

2021-06-16 22:45 UTC, garyschulte commented on docs/Concepts/Transactions/Transaction-Types.md
> +[EIP-1559 fee market changes](#eip1559-transactions).
similar thoughts about the use of 'compatibility' here.  Access list txns will continue to work, they just won't benefit from 1559 fee market changes.

2021-06-16 22:45 UTC, garyschulte commented on docs/Concepts/Transactions/Transaction-Types.md
> +`EIP1559` transactions contain, along with the [legacy parameters](#frontier-transactions) and
legacy parameters other than gasPrice.  You do address this elsewhere though.

2021-06-16 22:45 UTC, garyschulte commented on docs/Reference/API-Objects.md
> +| **accessList**           | Array               | List of addresses and storage keys the transaction plans to access. Used in [`ACCESS_LIST` transactions](../Concepts/Transactions/Transaction-Types.
do we have a way to mark these as nullable or optional?  same q for gasPrice, maxFeePerGas, maxPriorityFeePerGas

2021-06-17 09:15 UTC, NicolasMassart approved these changes
Looks good to me.

2021-06-17 09:15 UTC, NicolasMassart commented on CI/vale/vale_styles/Vocab/Besu/accept.txt
> +[iI]ncentiviz(e|es|ed|ing)
Regex should not contain capture groups and be
```
[iI]ncentiviz(?:e|es|ed|ing)
```

2021-06-17 15:52 UTC, garyschulte approved these changes
LGTM, thanks

2021-06-17 16:15 UTC, merged