add fast-sync peer recommendation
hyperledger/besu-docs pull request #805
Opened 2021-09-17 16:02 UTC by rolandtyler

Signed-off-by: Roland Tyler <roland.tyler@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change
Add new minimum number of peers to fast sync.

## Issue fixed
Fixes #796 

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-09-20 22:12 UTC, garyschulte requested changes
LGTM, minor ask

2021-09-21 17:53 UTC, alexandratran approved these changes
Minor suggestion, lgtm

2021-09-21 17:53 UTC, alexandratran commented on docs/Concepts/Node-Types.md
> +    [`fast-sync-min-peers`](../Reference/CLI/CLI-Syntax.md#fast-sync-min-peers) to increase the number of peers to at least 8.
```suggestion
    the [`--fast-sync-min-peers`](../Reference/CLI/CLI-Syntax.md#fast-sync-min-peers) command line option to increase the number of peers to at least 8.
```

2021-09-23 03:22 UTC, bgravenorst commented on docs/Concepts/Node-Types.md
> +    To improve performace, or if the fast sync is taking a long time to complete, use
typo, "performance"

2021-09-23 03:27 UTC, bgravenorst approved these changes
Approved, but please fix the typo.

2021-09-29 19:05 UTC, garyschulte approved these changes
🚢

2021-09-29 19:06 UTC, merged