Incorporate feedback
hyperledger/besu-docs pull request #900
Opened 2021-12-09 20:25 UTC by rolandtyler

Signed-off-by: Roland Tyler <roland.tyler@consensys.net>

## Pull request checklist

Use the following list to make sure your PR fits the Besu doc quality standard.

### Before creating the pull request

Make sure that:

- [ ] [all commits in this PR are signed off for the DCO](https://wiki.hyperledger.org/display/BESU/DCO).
- [ ] you read the [contribution guidelines](https://wiki.hyperledger.org/display/BESU/Contributing+to+documentation).
- [ ] you have [tested your changes locally](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewTheDocumentation) before submitting them to the community for review.

### After creating your pull request and tests finished

Make sure that:

- [ ] you fixed all the issues raised by the tests, if any.
- [ ] you verified the rendering of your changes on [ReadTheDocs.org PR preview](https://wiki.hyperledger.org/display/BESU/MkDocs+And+Markdown+Guide#MkDocsAndMarkdownGuide-PreviewwithReadTheDocs)
  and updated the testing link (see [Testing](#testing)).

## Describe the change

## Issue fixed

## Impacted parts 

### For content changes

- [ ] Doc content
- [ ] Doc pages organisation

### For tools changes

- [ ] CircleCI workflow
- [ ] Build and QA tools (lint, vale,…)
- [ ] MkDocs templates
- [ ] MkDocs configuration
- [ ] Python dependencies
- [ ] Node dependencies and JavaScript
- [ ] ReadTheDocs configuration
- [ ] GitHub integration

## Testing

## Screenshots / recording

2021-12-13 23:28 UTC, macfarla requested changes
config file version for list options need [] around them

2021-12-16 21:35 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
> +    rpc-http-tls-protocol=["TLSv1.3,TLSv1.2"]
I think you want to have a list of strings. Did you try it?
    rpc-http-tls-protocol=["TLSv1.3","TLSv1.2"]

2021-12-16 21:36 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
> +    rpc-http-tls-cipher-suite=["TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]
same here

2021-12-16 21:36 UTC, macfarla commented on docs/Reference/CLI/CLI-Syntax.md
> +    rpc-http-tls-cipher-suite=["TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]
rpc-http-tls-cipher-suite=["TLS_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]

2021-12-16 22:14 UTC, macfarla approved these changes

2021-12-17 03:24 UTC, alexandratran commented on docs/HowTo/Configure/TLS/Configure-TLS.md
> +  [`--rpc-http-tls-protocol`](../../../Reference/CLI/CLI-Syntax.md#rpc-http-tls-protocol-rpc-http-tls-protocols) option.
```suggestion
* Specifies the Java cipher suites using the
  [`--rpc-http-tls-cipher-suite`](../../../Reference/CLI/CLI-Syntax.md#rpc-http-tls-cipher-suite-rpc-http-tls-cipher-suites) option.
* Specifies the TLS protocol version using the
  [`--rpc-http-tls-protocol`](../../../Reference/CLI/CLI-Syntax.md#rpc-http-tls-protocol-rpc-http-tls-protocols) option.
```

Note consistency with the rest of this list.

2021-12-17 03:24 UTC, alexandratran commented on docs/Reference/CLI/CLI-Syntax.md
> +A list of comma separated TLS cipher suites to support.
```suggestion
A list of comma-separated TLS cipher suites to support.
```

Maybe note here whether the singular and plural aliases can be used interchangeably, or a plural list requires the plural alias.

2021-12-17 03:24 UTC, alexandratran commented on docs/Reference/CLI/CLI-Syntax.md
> +A list of comma separated TLS protocols to support. Defaults to `DEFAULT_TLS_PROTOCOLS`, a list which includes `TLSv1.3` and `TLSv1.2`.
```suggestion
A list of comma-separated TLS protocols to support. The default is `DEFAULT_TLS_PROTOCOLS`, a list which includes `TLSv1.3` and `TLSv1.2`.
```

Same comment about singular vs. plural alias.

2021-12-20 19:07 UTC, alexandratran approved these changes
Final suggestions

2021-12-20 19:07 UTC, alexandratran commented on docs/Reference/CLI/CLI-Syntax.md
> +    the same option.
```suggestion
!!! note

    You can use `--rpc-http-tls-cipher-suite` and `--rpc-http-tls-cipher-suites` interchangeably.
```

2021-12-20 19:07 UTC, alexandratran commented on docs/Reference/CLI/CLI-Syntax.md
> +    the same option.
```suggestion
!!! note

    You can use `--rpc-http-tls-protocol` and `--rpc-http-tls-protocols` interchangeably.
```

2021-12-20 19:15 UTC, merged